In [1]:
import numpy as np

inputs = np.array([[0,0,1],
                   [1,1,0],
                   [0,1,1],
                   [1,0,1]])

outputs = np.array([[0],
                    [1],
                    [0],
                    [1]])

print(inputs)
outputs


[[0 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 1]]


array([[0],
       [1],
       [0],
       [1]])

In [2]:
# Step 3: Initialize Weights Randomly
np.random.seed(10)
weights = np.random.random((3,1))
weights


array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [3]:
# Step 4: Apply Activation Function (Sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(5)


np.float64(0.9933071490757153)

In [4]:
# Step 5: Compute Weighted Sum
sum = np.dot(inputs, weights) + 0.02
ypred = sigmoid(sum)
ypred


array([[0.65783211],
       [0.69255099],
       [0.66248773],
       [0.8061162 ]])

In [5]:
# Step 6: Calculate Error
sum = np.dot(inputs, weights) + 0.02
ypred = sigmoid(sum)

error = outputs - ypred
error


array([[-0.65783211],
       [ 0.30744901],
       [-0.66248773],
       [ 0.1938838 ]])

In [6]:
# Step 7: Define Gradient Function
def gradient(x):
    return x * (1 - x)

sum = np.dot(inputs, weights) + 0.02
ypred = sigmoid(sum)
error = outputs - ypred


In [7]:
# Step 8: Weight Update (Backpropagation)
adjustment = error * gradient(ypred)         # Gradient Descent
weights = weights + np.dot(inputs.T, adjustment)   # Backpropogation
error


array([[-0.65783211],
       [ 0.30744901],
       [-0.66248773],
       [ 0.1938838 ]])

In [8]:
# Check shapes
inputs.T.shape
adjustment.shape


(4, 1)

In [9]:
# Step 9: Train for Multiple Epochs (1500 iterations)
for i in range(1500):
    sum = np.dot(inputs, weights) + 0.02
    ypred = sigmoid(sum)
    error = outputs - ypred
    adjustment = error * gradient(ypred)
    weights = weights + np.dot(inputs.T, adjustment)

error   # Final Error


array([[-0.03112643],
       [ 0.00289382],
       [-0.00939389],
       [ 0.02648377]])

In [10]:
# Step 10: Final Predictions (Round to 0 or 1)
ypred.round()


array([[0.],
       [1.],
       [0.],
       [1.]])