<a href="https://colab.research.google.com/github/Prakshil/Machine_learning/blob/main/Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **A. Numpy Exercises**

In [ ]:
import numpy as np

## 1. Basic Array Creation & Manipulation

• Create a 1D array of numbers from 1 to 20.

• Create a 3×4 matrix of ones and reshape it to 4×3.

• Create a 5×5 identity matrix.

• Generate 15 equally spaced numbers between 5 and 50.

• Generate a 4×4 matrix of random integers between 1 and 100.

In [ ]:
array = np.arange(1,21)
print(array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
array = np.ones((3,4))
print(array)
array = array.reshape(4,3)
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
array = np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
array = np.linspace(5,50,15,)
print(array)

[ 5.          8.21428571 11.42857143 14.64285714 17.85714286 21.07142857
 24.28571429 27.5        30.71428571 33.92857143 37.14285714 40.35714286
 43.57142857 46.78571429 50.        ]


In [ ]:
array = np.random.randint(1,101,(4,4))
print(array)

[[95 82 30 94]
 [43 33 14 81]
 [99 76 67 91]
 [63 33 99 31]]


### 2. Indexing, Slicing, and Broadcasting
• Create a 3×3 matrix of random integers between 1 and 100

• Extract: First row, Second column, Center element.

• Replace all values greater than 50 in a matrix with 999.

• Multiply a 1D array of size 5 (random integers between 1 to 10) by 10 using
broadcasting.

In [ ]:
array = np.random.randint(1,101,(3,3))
print(array)

[[ 9 84 63]
 [77 68 67]
 [20 83 40]]


In [ ]:
print(array[0])
print(array[:,1:2])
print(array[1,1])


[ 9 84 63]
[[84]
 [68]
 [83]]
68


In [ ]:
array[array > 50] = 999
print(array)

[[  9 999 999]
 [999 999 999]
 [ 20 999  40]]


In [ ]:
arr1 = np.random.randint(1,11,5)
print(arr1)
arr2 = 10
print(arr1*arr2)

[1 9 3 6 8]
[10 90 30 60 80]


## 3. Mathematical and Statistical Operations

• Create a 3×3 matrix of random integers between 1 and 100

• Compute sum, mean, median, std, var, min, and max of the above array.

• Normalize a 1D array

In [ ]:
arr = np.random.randint(1,101,(3,3))
print(arr)

[[20  5 18]
 [40 53 42]
 [89 76 95]]


In [ ]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

438
48.666666666666664
42.0


In [ ]:
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

30.41929212413289
925.3333333333334
5
95


In [ ]:
arr2 = np.random.randint(1,11,5)
print(arr2)
arr2 = (arr2 - np.min(arr2)) / (np.max(arr2) - np.min(arr2))
print(arr2)

[ 3  2 10  3  9]
[0.125 0.    1.    0.125 0.875]


## 4. NumPy Matrix Operations and Linear Algebra

• Generate Following two NumPy matrix import numpy as np

A = ([4, 2], [1, 3])

B = ([2, 0], [1, 5])

• Find matrix multiplication of A and B.

• Find dot product of A and B.

• Find element wise addition/ subtraction/ multiplications/ division of A and B

• Transpose matrix A.

• Compute determinant of A.

• Compute inverse of A (if possible).

• Find eigenvalues and eigenvectors.

• Solve the system of equations:

2x + y = 8

3x + 4y = 18

In [ ]:
A = np.array([[4, 2], [1, 3]])
B = np.array([[2, 1], [1, 5]])

print("Matrix Multiplication:")
print(A*B)

Matrix Multiplication:
[[ 8  2]
 [ 1 15]]


In [ ]:
print("\nDot Product:")
print(np.dot(A, B))


Dot Product:
[[10 14]
 [ 5 16]]


In [ ]:
print("\nElement Wise Addition:")
print(A+B)
print("\nElement Wise Subtraction:")
print(A-B)
print("\nElement Wise Multiplication:")
print(A*B)
print("\nElement Wise Division:")
print(A/B)


Element Wise Addition:
[[6 3]
 [2 8]]

Element Wise Subtraction:
[[ 2  1]
 [ 0 -2]]

Element Wise Multiplication:
[[ 8  2]
 [ 1 15]]

Element Wise Division:
[[2.  2. ]
 [1.  0.6]]


In [ ]:
print(A.T)


[[4 1]
 [2 3]]


In [ ]:
print(np.linalg.det(A))

10.000000000000002


In [ ]:
print(np.linalg.inv(A))


[[ 0.3 -0.2]
 [-0.1  0.4]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
A = np.array([[2, 1], [3, 4]])
B = np.array([8, 18])
solution = np.linalg.solve(A, B)
print("Solution (x, y):", solution)

Solution (x, y): [2.8 2.4]


## **B. Pandas Exercises**

In [ ]:
import pandas as pd

## 1.Series & DataFrame Basics

• Given the following list of marks: [78, 85, 92, 70, 66]

Create a Pandas Series and assign the following student names as indices: ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha']

Display the Series













In [ ]:
data = [78,52,92,70,66 ]
index =['amit', 'Bhavna', 'Chetan ', 'Divya', 'Esha']
new = pd.Series(data, index = index )
print(new)

amit       78
Bhavna     52
Chetan     92
Divya      70
Esha       66
dtype: int64


# 2. Using the following dictionary:

data = {

 'Name': ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha'],

 'Gender': ['Male', 'Female', 'Male', 'Female', 'Female'],

 'Math': [78, 85, 92, 70, 66],

 'Science': [88, 79, 95, 72, 60]

}


Create a Pandas DataFrame and display:

• The full DataFrame

• The column names

• The shape of the DataFrame

In [ ]:
newdata = {
 'Name': ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha'],
 'Gender': ['Male', 'Female', 'Male', 'Female', 'Female'],
 'Math': [78, 85, 92, 70, 66],
 'Science': [88, 79, 95, 72, 60]
}

In [ ]:
df=pd.DataFrame(newdata)
print(df)


     Name  Gender  Math  Science
0    Amit    Male    78       88
1  Bhavna  Female    85       79
2  Chetan    Male    92       95
3   Divya  Female    70       72
4    Esha  Female    66       60


In [ ]:
print(df.columns)

Index(['Name', 'Gender', 'Math', 'Science'], dtype='object')


In [ ]:
print(df.shape)

(5, 4)


## 2.Data Exploration

• Load the dataset from this url "https://archive.ics.uci.edu/ml/machine-learningdatabases/autos/imports-85.data"

• Assign names of columns:

["symboling","normalized-losses","make","fuel-type","aspiration", "num-ofdoors","body-style", "drive-wheels","engine-location","wheelbase","length","width","height","curb-weight","engine-type","num-of-cylinders",
"engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
"peak-rpm","city-mpg","highway-mpg","price"]

• Display .shape, .columns, .info(), and .describe().

• Display only ","width","height","curb-weight","engine-type" columns.

• Display car details which have num-of-doors = four


In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
columns = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-ofdoors","body-style", "drive-wheels","engine-location","wheelbase","length","width","height","curb-weight","engine-type","num-of-cylinders",
"engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
"peak-rpm","city-mpg","highway-mpg","price"]


In [ ]:
ndf = pd.read_csv(url , names = columns, delimiter = ",", na_values = '?')
print(ndf.head(10))

   symboling  normalized-losses         make fuel-type aspiration num-ofdoors  \
0          3                NaN  alfa-romero       gas        std         two   
1          3                NaN  alfa-romero       gas        std         two   
2          1                NaN  alfa-romero       gas        std         two   
3          2              164.0         audi       gas        std        four   
4          2              164.0         audi       gas        std        four   
5          2                NaN         audi       gas        std         two   
6          1              158.0         audi       gas        std        four   
7          1                NaN         audi       gas        std        four   
8          1              158.0         audi       gas      turbo        four   
9          0                NaN         audi       gas      turbo         two   

    body-style drive-wheels engine-location  wheelbase  ...  engine-size  \
0  convertible          rwd     

In [ ]:
print(ndf.shape)

(205, 26)


In [ ]:
print(ndf.columns)

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-ofdoors', 'body-style', 'drive-wheels', 'engine-location',
       'wheelbase', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')


In [ ]:
print(ndf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-ofdoors        203 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheelbase          205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
print(ndf.describe())

        symboling  normalized-losses   wheelbase      length       width  \
count  205.000000         164.000000  205.000000  205.000000  205.000000   
mean     0.834146         122.000000   98.756585  174.049268   65.907805   
std      1.245307          35.442168    6.021776   12.337289    2.145204   
min     -2.000000          65.000000   86.600000  141.100000   60.300000   
25%      0.000000          94.000000   94.500000  166.300000   64.100000   
50%      1.000000         115.000000   97.000000  173.200000   65.500000   
75%      2.000000         150.000000  102.400000  183.100000   66.900000   
max      3.000000         256.000000  120.900000  208.100000   72.300000   

           height  curb-weight  engine-size        bore      stroke  \
count  205.000000   205.000000   205.000000  201.000000  201.000000   
mean    53.724878  2555.565854   126.907317    3.329751    3.255423   
std      2.443522   520.680204    41.642693    0.273539    0.316717   
min     47.800000  1488.000000 

In [ ]:
cols = ndf[["width","height","curb-weight","engine-type"]]
print(cols)

     width  height  curb-weight engine-type
0     64.1    48.8         2548        dohc
1     64.1    48.8         2548        dohc
2     65.5    52.4         2823        ohcv
3     66.2    54.3         2337         ohc
4     66.4    54.3         2824         ohc
..     ...     ...          ...         ...
200   68.9    55.5         2952         ohc
201   68.8    55.5         3049         ohc
202   68.9    55.5         3012        ohcv
203   68.9    55.5         3217         ohc
204   68.9    55.5         3062         ohc

[205 rows x 4 columns]


In [ ]:
doors = ndf[ndf['num-ofdoors'] == "four"]
print(doors)

     symboling  normalized-losses   make fuel-type aspiration num-ofdoors  \
3            2              164.0   audi       gas        std        four   
4            2              164.0   audi       gas        std        four   
6            1              158.0   audi       gas        std        four   
7            1                NaN   audi       gas        std        four   
8            1              158.0   audi       gas      turbo        four   
..         ...                ...    ...       ...        ...         ...   
200         -1               95.0  volvo       gas        std        four   
201         -1               95.0  volvo       gas      turbo        four   
202         -1               95.0  volvo       gas        std        four   
203         -1               95.0  volvo    diesel      turbo        four   
204         -1               95.0  volvo       gas      turbo        four   

    body-style drive-wheels engine-location  wheelbase  ...  engine-size  \

## 3. Missing values handling


• Missing value is represented by ‘?’ in this dataset. Replace it with NULL.

• Check how many missing values are there in each attribute.

• Replace missing values of "normalized-losses", "stroke", "bore", "horsepower" with mean.

• Drop all the rows which has missing value in attribute “price”.

• Replace missing values of “num-of-doors” with mode.

• Replace all other missing values with median.


In [ ]:
print(ndf.fillna(value="NULL"))

     symboling normalized-losses         make fuel-type aspiration  \
0            3              NULL  alfa-romero       gas        std   
1            3              NULL  alfa-romero       gas        std   
2            1              NULL  alfa-romero       gas        std   
3            2             164.0         audi       gas        std   
4            2             164.0         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1              95.0        volvo       gas        std   
201         -1              95.0        volvo       gas      turbo   
202         -1              95.0        volvo       gas        std   
203         -1              95.0        volvo    diesel      turbo   
204         -1              95.0        volvo       gas      turbo   

    num-ofdoors   body-style drive-wheels engine-location  wheelbase  ...  \
0           two  convertible          rwd           front       88.6  ...   
1    

In [ ]:
attr = ndf.isnull().sum()
print(attr)

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-ofdoors           2
body-style            0
drive-wheels          0
engine-location       0
wheelbase             0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64


In [ ]:
ndf ["normalized-losses"] = ndf["normalized-losses"].fillna(ndf["normalized-losses"].mean())
ndf["stroke"] = ndf["stroke"].fillna(ndf["stroke"].mean())
ndf["bore"] = ndf["bore"].fillna(ndf["bore"].mean())
ndf["horsepower"] = ndf["horsepower"].fillna(ndf["horsepower"].mean())

print(ndf.head(5))

   symboling  normalized-losses         make fuel-type aspiration num-ofdoors  \
0          3              122.0  alfa-romero       gas        std         two   
1          3              122.0  alfa-romero       gas        std         two   
2          1              122.0  alfa-romero       gas        std         two   
3          2              164.0         audi       gas        std        four   
4          2              164.0         audi       gas        std        four   

    body-style drive-wheels engine-location  wheelbase  ...  engine-size  \
0  convertible          rwd           front       88.6  ...          130   
1  convertible          rwd           front       88.6  ...          130   
2    hatchback          rwd           front       94.5  ...          152   
3        sedan          fwd           front       99.8  ...          109   
4        sedan          4wd           front       99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepowe

In [ ]:
print(ndf[ndf["price"].isnull()])
ndf = ndf.dropna(subset=['price'])

     symboling  normalized-losses     make fuel-type aspiration num-ofdoors  \
9            0              122.0     audi       gas      turbo         two   
44           1              122.0    isuzu       gas        std         two   
45           0              122.0    isuzu       gas        std        four   
129          1              122.0  porsche       gas        std         two   

    body-style drive-wheels engine-location  wheelbase  ...  engine-size  \
9    hatchback          4wd           front       99.5  ...          131   
44       sedan          fwd           front       94.5  ...           90   
45       sedan          fwd           front       94.5  ...           90   
129  hatchback          rwd           front       98.4  ...          203   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
9           mpfi  3.13    3.40               7.0      160.0    5500.0   
44          2bbl  3.03    3.11               9.6       70.0    5400.0   
45  

In [ ]:
ndf["num-ofdoors"] = ndf["num-ofdoors"].fillna(ndf["num-ofdoors"].mode()[0])
print(ndf.head(5))

   symboling  normalized-losses         make fuel-type aspiration num-ofdoors  \
0          3              122.0  alfa-romero       gas        std         two   
1          3              122.0  alfa-romero       gas        std         two   
2          1              122.0  alfa-romero       gas        std         two   
3          2              164.0         audi       gas        std        four   
4          2              164.0         audi       gas        std        four   

    body-style drive-wheels engine-location  wheelbase  ...  engine-size  \
0  convertible          rwd           front       88.6  ...          130   
1  convertible          rwd           front       88.6  ...          130   
2    hatchback          rwd           front       94.5  ...          152   
3        sedan          fwd           front       99.8  ...          109   
4        sedan          4wd           front       99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepowe

/tmp/ipython-input-41-3827722714.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ndf["num-ofdoors"] = ndf["num-ofdoors"].fillna(ndf["num-ofdoors"].mode()[0])


In [ ]:
ndf["peak-rpm"] = ndf["peak-rpm"].fillna(ndf["peak-rpm"].median())

print(ndf.isnull().sum())

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-ofdoors          0
body-style           0
drive-wheels         0
engine-location      0
wheelbase            0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64


/tmp/ipython-input-42-1092858644.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ndf["peak-rpm"] = ndf["peak-rpm"].fillna(ndf["peak-rpm"].median())


## 4.Grouping, Sorting, and Aggregation



*   Group by “Fuel-type” and compute average price.
*    In our dataset, the fuel consumption columns "city-mpg" and "highway-mpg" are represented by mpg (miles per gallon) unit.


Assume we are developing an application in a country that accept the fuel consumption with L/100km standard We will need to apply data transformation to transform mpg into L/100km? The formula for unit conversion is L/100km = 235 / mpg -Sort the DataFrame based on “price” in descending order.

In [ ]:
fuel_price = ndf.groupby('fuel-type')['price'].mean()
print(fuel_price)

fuel-type
diesel    15838.15000
gas       12916.40884
Name: price, dtype: float64


 conversion formula: L/100km = 235 / mpg

In [ ]:
ndf['city-L/100km'] = 235 / ndf['city-mpg']
ndf['highway-L/100km'] = 235 / ndf['highway-mpg']
print(ndf[['city-mpg', 'city-L/100km', 'highway-mpg', 'highway-L/100km']].head())

   city-mpg  city-L/100km  highway-mpg  highway-L/100km
0        21     11.190476           27         8.703704
1        21     11.190476           27         8.703704
2        19     12.368421           26         9.038462
3        24      9.791667           30         7.833333
4        18     13.055556           22        10.681818


/tmp/ipython-input-44-3429278430.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ndf['city-L/100km'] = 235 / ndf['city-mpg']


In [ ]:
ndf_sorted = ndf.sort_values(by='price', ascending=False)
print(ndf_sorted["price"].head(7))

74     45400.0
16     41315.0
73     40960.0
128    37028.0
17     36880.0
49     36000.0
48     35550.0
Name: price, dtype: float64
